public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJN8+yUWGBvFTxQbDIII+spxpmgLIQPaow3bGpicu9Z8QRxODDisFbZoLraNwVkxrLkAS9dCQvxR4v3LfnsMGq8CAwEAAQ==
spring:
  datasource:
    druid:
      connect-properties: config.decrypt=true;config.decrypt.key=${public-key}
      filter:
        config:
          enabled: true
        filters: conn,config,stat,slf4j
        initial-size: 5
        max-active: 5
        min-idle: 5
        test-on-borrow: true
        test-on-return: true
        test-while-idle: true
      password: WrKNw2hnwocthf63j5fs2ooOJjfIgn0LGAED4OxHxVF/VoDCU5YNddiITZ/N1/T4SoErD6jYJ/yGg6u4+fwt+w==
      url: jdbc:mysql://39.97.209.17:3306/cxl
      username: root
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      host: 39.97.209.17
      port: 27017
      database: cxl